---
apiVersion: v1
kind: Service
metadata:
  name: ventilar-db-svc
spec:
  type: ClusterIP
  selector: # que Pods o service vai buscar
    app: ventilar-db
  ports:
    - protocol: TCP
      port: 5432 # this I can choose any, but usually the same value is selected
      targetPort: 5432 # this must be the deployment port to reference
