apiVersion: v1
kind: Secret
metadata:
  name: ventilar-secret
type: Opaque
data:
  # e.g. postgres://admin:admin@10.43.22.86:5432/ventilar_db?sslmode=disable
  DB_URL: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbkAxMC40My4yMi44Njo1NDMyL3ZlbnRpbGFyX2RiP3NzbG1vZGU9ZGlzYWJsZQo=
  DB_USER: YWRtaW4K
  DB_NAME: dmVudGlsYXJfZGIK
  DB_PASSW: YWRtaW4K
  atlas.hcl: ZW52ICJrOHMiIHsKICB1cmwgPSAicG9zdGdyZXM6Ly9hZG1pbjphZG1pbkAxMC40My4yMi44Njo1NDMyL3ZlbnRpbGFyX2RiP3NzbG1vZGU9ZGlzYWJsZSIKfQo=
