# read: https://atlasgo.io/guides/testing/github-actions
name: Integration Test (Postgres)
on:
  push:
jobs:
  integration:
    runs-on: ubuntu-latest
    # deploys a test db using docker containers
    services:
      postgres:
        image: postgres:15.1-alpine
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    # pipeline
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Install Atlas
        run: |
          curl -sSf https://atlasgo.sh | sh
      - name: Run migratrions
        run: |
          atlas migrate apply --dir file://database/migrations/ -u 'postgres://postgres:pass@localhost:5432/test?sslmode=disable'
      - name: Starts Api Server
        run: |
          make run
      - name: Run tests
        run: |
          make test
