name: Unit Test
on:
  push:
    paths-ignore:
      - 'README.md'
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Run tests
        run: |
          make test
